Fix 'worker_use_ray' not found in vLLM 0.7.0
Related to https://github.com/vllm-project/vllm/pull/12383

`--worker-use-ray` is deprecated since 0.4.3:
https://github.com/vllm-project/vllm/commit/676a99982fe9aabe72fd52a91e08988a653a7359

```log
Exception raised in creation task: The actor died because of an error raised in its creation task, [36mray::LLMRayActor.__init__()[39m (repr=<openrlhf.trainer.ray.vllm_engine.LLMRayActor object at 0x150cf7b4b910>)
 File "openrlhf/trainer/ray/vllm_engine.py", line 58, in __init__
 self.llm = vllm.LLM(*args, **kwargs)
 File "vllm/utils.py", line 1039, in inner
 return fn(*args, **kwargs)
 File "vllm/entrypoints/llm.py", line 210, in __init__
 engine_args = EngineArgs(
TypeError: EngineArgs.__init__() got an unexpected keyword argument 'worker_use_ray'
```

Signed-off-by: Hollow Man <hollowman@opensuse.org>